"""
Auto-generated routing tests — exhaustive per exemplar and app.

Loads test queries from data/test_queries.jsonl (generated by discover.py)
and verifies each query routes to the expected action.

Two levels of assertion:
  1. STRICT: top-1 match is the expected action_key (exact action)
  2. APP:    top-1 match is from the expected app (right app, maybe wrong action)

Both are tested. APP failures are the critical ones — they mean the wrong
service entirely. STRICT failures within the same app are less severe
(e.g., routing to jira-update-issue instead of jira-create-issue).
"""

import json
import sys
from pathlib import Path

import pytest

MODEL_DIR = Path(__file__).parent.parent
sys.path.insert(0, str(MODEL_DIR))

RUNTIME_DIR = MODEL_DIR.parent.parent / "glyphh-runtime"
if RUNTIME_DIR.exists():
    sys.path.insert(0, str(RUNTIME_DIR))

TEST_QUERIES_PATH = MODEL_DIR / "data" / "test_queries.jsonl"


# ---------------------------------------------------------------------------
# Load test queries
# ---------------------------------------------------------------------------

def _load_test_queries() -> list[dict]:
    """Load all test queries from the auto-generated JSONL file."""
    if not TEST_QUERIES_PATH.exists():
        return []
    queries = []
    with open(TEST_QUERIES_PATH) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            queries.append(json.loads(line))
    return queries


def _load_exemplars_and_encoder():
    """Load encoder + all exemplar glyphs (cached across tests)."""
    from glyphh.encoder import Encoder
    from glyphh.core.types import Concept
    from encoder import ENCODER_CONFIG, entry_to_record

    encoder = Encoder(ENCODER_CONFIG)
    exemplar_path = MODEL_DIR / "data" / "exemplars.jsonl"
    if not exemplar_path.exists():
        return encoder, []

    glyphs = []
    with open(exemplar_path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            entry = json.loads(line)
            record = entry_to_record(entry)
            glyph = encoder.encode(Concept(
                name=record["concept_text"],
                attributes=record["attributes"],
            ))
            glyphs.append((glyph, record))
    return encoder, glyphs


def _route(query_text: str, encoder, glyphs) -> tuple[str, str, float]:
    """Route a query and return (action_key, app_slug, score)."""
    from glyphh.core.types import Concept
    from glyphh.core.ops import cosine_similarity as cos_sim
    from encoder import encode_query

    record = encode_query(query_text)
    query_glyph = encoder.encode(Concept(
        name=record["name"],
        attributes=record["attributes"],
    ))

    best_score = -1.0
    best_action_key = ""
    best_app_slug = ""

    for glyph, rec in glyphs:
        total_sim = 0.0
        total_weight = 0.0

        for layer_name in query_glyph.layers:
            if layer_name not in glyph.layers:
                continue
            q_layer = query_glyph.layers[layer_name]
            e_layer = glyph.layers[layer_name]
            layer_weight = 0.4 if layer_name == "intent" else 0.6

            for seg_name in q_layer.segments:
                if seg_name not in e_layer.segments:
                    continue
                q_seg = q_layer.segments[seg_name]
                e_seg = e_layer.segments[seg_name]

                for role_name in q_seg.roles:
                    if role_name not in e_seg.roles:
                        continue
                    sim = float(cos_sim(
                        q_seg.roles[role_name].data,
                        e_seg.roles[role_name].data,
                    ))
                    role_weight = {
                        "action": 1.0, "target": 0.7, "domain": 0.8,
                        "description": 1.0, "keywords": 0.8,
                    }.get(role_name, 1.0)
                    total_sim += sim * layer_weight * role_weight
                    total_weight += layer_weight * role_weight

        score = total_sim / total_weight if total_weight > 0 else 0.0
        if score > best_score:
            best_score = score
            best_action_key = rec["metadata"]["action_key"]
            best_app_slug = rec["metadata"]["app_slug"]

    return best_action_key, best_app_slug, best_score


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def routing_env():
    """Encoder + encoded exemplars, cached for the entire test module."""
    encoder, glyphs = _load_exemplars_and_encoder()
    if not glyphs:
        pytest.skip("No exemplars — run discover.py first")
    return encoder, glyphs


# ---------------------------------------------------------------------------
# Parametrized tests — one per test query
# ---------------------------------------------------------------------------

_ALL_QUERIES = _load_test_queries()


def _test_id(tq: dict) -> str:
    """Generate a readable test ID like 'slack_bot-send-message[canonical]'."""
    return f"{tq['expected_action_key']}[{tq['test_type']}]"


@pytest.mark.parametrize("tq", _ALL_QUERIES, ids=[_test_id(q) for q in _ALL_QUERIES])
def test_routes_to_correct_app(tq, routing_env):
    """Top-1 match must be from the correct app (critical — wrong app = wrong service)."""
    encoder, glyphs = routing_env
    action_key, app_slug, score = _route(tq["query"], encoder, glyphs)
    expected_app = tq["expected_app_slug"]
    assert app_slug == expected_app, (
        f"Query: {tq['query']!r}\n"
        f"  Expected app: {expected_app}\n"
        f"  Got: {app_slug} ({action_key}, score={score:.3f})"
    )


@pytest.mark.parametrize("tq", _ALL_QUERIES, ids=[_test_id(q) for q in _ALL_QUERIES])
def test_routes_to_correct_action(tq, routing_env):
    """Top-1 match must be the exact expected action (strict — same app wrong action is softer)."""
    encoder, glyphs = routing_env
    action_key, app_slug, score = _route(tq["query"], encoder, glyphs)
    expected = tq["expected_action_key"]
    assert action_key == expected, (
        f"Query: {tq['query']!r}\n"
        f"  Expected: {expected}\n"
        f"  Got: {action_key} ({app_slug}, score={score:.3f})"
    )
